### ISSUE TITLE
Config Merging Strategies (Flat and Recursive)

### ISSUE THREAD

**Issue by PandaHugMonster** [PandaHugMonster/py-simputils-config#22]
Current implementation allows only "flat merging" which means that the `ConfigStore` values are merged only on the first level.
Any previous value on the first level is simply overwritten with the new value.

That means if YAML or JSON used with a tree of objects, dicts, lists are being simply overwritten.

The functionality that should be implemented during this ticket suppose to provide a way to merge multidimensional structures
based on a chosen strategy for the merge.

## The following strategies are planned:
- [x] #25
  - The way it is currently implemented. But some improvement in architecture is required
  - ![merging-strategies-Flat Strategy drawio](https://github.com/PandaHugMonster/py-simputils-config/assets/5005505/1f3099aa-86f8-476d-b494-2ad265cde579)
- [x] #23
  - (default) Replace List Recursive Strategy    
    ![merging-strategies-Recursive Strategy, List Replace drawio](https://github.com/PandaHugMonster/py-simputils-config/assets/5005505/e32e1dc8-cb5a-4635-972b-82fee686a0b0)

  - Extend List Recursive Strategy    
    ![merging-strategies-Recursive Strategy, List Extend drawio](https://github.com/PandaHugMonster/py-simputils-config/assets/5005505/2547ac0e-b55f-4a89-805d-6465a0180a42)

## TODO

- [x] Implement basic functionality
- [x] Implement different strategies (preferably in a flexible class-based manner, so users could write their own strategies)
- [x] Prepare documentation
- [x] Cover with tests

**Comment by PandaHugMonster** [comment]
- [ ] Consider behaviour for "Objects" in different strategies
